version: "3.7"
services:
  product-service:
    image: postgres:11.5-alpine
    container_name: 'product-service-postgresql'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-db
    volumes:
      - product-service-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  product-service-db: